/**
 * Tabelas de domínio do documento JSON da prestação de contas (Fase V).
 *
 * **GERADO AUTOMATICAMENTE — não edite à mão.** Rode `npm run dominios:fase-v`
 * no backend após atualizar os schemas em `src/infrastructure/tcesp/schemas/`.
 *
 * Fonte: JSON Schema oficial do Audesp, versão v1.14 — a mesma que o TCESP
 * usa para validar o documento no envio. Portanto código fora destas tabelas é
 * rejeitado na transmissão, e aqui é tratado como **erro**, não aviso.
 *
 * Os rótulos são os do próprio schema (campo `examples`).
 */

import type { Opcao } from './dominios';

/** Documentos fiscais — `categoria_despesas_tipo`. */
export const CATEGORIA_DESPESA: Opcao[] = [
  { value: '1', label: 'BENS E MATERIAIS PERMANENTES - BENS E EQUIPAMENTOS DE INFORMÁTICA' },
  { value: '2', label: 'BENS E MATERIAIS PERMANENTES - BENS E EQUIPAMENTOS HOSPITALARES' },
  { value: '3', label: 'BENS E MATERIAIS PERMANENTES - OUTROS BENS E MATERIAIS PERMANENTES' },
  { value: '4', label: 'DESPESAS FINANCEIRAS E BANCÁRIAS - DESPESAS BANCÁRIAS PAGAS' },
  { value: '5', label: 'DESPESAS FINANCEIRAS E BANCÁRIAS - IOF PAGO' },
  { value: '6', label: 'DESPESAS FINANCEIRAS E BANCÁRIAS - JUROS PAGOS' },
  { value: '7', label: 'DESPESAS FINANCEIRAS E BANCÁRIAS - OUTRAS DESPESAS FINANCEIRAS E BANCÁRIAS' },
  { value: '8', label: 'DIVERSOS - DIVERSOS' },
  { value: '9', label: 'GASTOS ADMINISTRATIVOS - COMBUSTÍVEL' },
  { value: '10', label: 'GASTOS ADMINISTRATIVOS - ESTACIONAMENTO/CONDUÇÃO/TÁXI' },
  { value: '11', label: 'GASTOS ADMINISTRATIVOS - MATERIAL DE EXPEDIENTE/CORREIO/FOTOCÓPIAS' },
  { value: '12', label: 'GASTOS ADMINISTRATIVOS - SEGUROS' },
  { value: '13', label: 'GASTOS ADMINISTRATIVOS - VIAGENS (HOTEL/PASSAGENS AÉREAS/PASS.RODOVIÁRIAS)' },
  { value: '14', label: 'GASTOS ADMINISTRATIVOS - OUTROS GASTOS ADMINISTRATIVOS' },
  { value: '15', label: 'GÊNEROS ALIMENTÍCIOS - GÊNEROS ALIMENTÍCIOS' },
  { value: '16', label: 'LOCAÇÃO - AMBULÂNCIAS' },
  { value: '17', label: 'LOCAÇÃO - DIVERSAS' },
  { value: '18', label: 'LOCAÇÃO - EQUIPAMENTO DE INFORMÁTICA' },
  { value: '19', label: 'LOCAÇÃO - EQUIPAMENTO MÉDICO HOSPITALAR' },
  { value: '20', label: 'LOCAÇÃO - IMÓVEL' },
  { value: '21', label: 'LOCAÇÃO - LAVANDERIA E ENXOVAL' },
  { value: '22', label: 'LOCAÇÃO - SISTEMA DE SOFTWARE' },
  { value: '23', label: 'LOCAÇÃO - VEÍCULOS' },
  { value: '24', label: 'MANUTENÇÃO - EQUIPAMENTO DE INFORMÁTICA' },
  { value: '25', label: 'MANUTENÇÃO - EQUIPAMENTO MÉDICO HOSPITALAR' },
  { value: '26', label: 'MANUTENÇÃO - PREDIAL E IMOBILIÁRIO' },
  { value: '27', label: 'MANUTENÇÃO - VEÍCULOS' },
  { value: '28', label: 'MANUTENÇÃO - OUTRAS MANUTENÇÕES' },
  { value: '29', label: 'MATERIAIS - MATERIAL DE HIGIENIZAÇÃO E LIMPEZA/UNIFORMES' },
  { value: '30', label: 'MATERIAIS - MATERIAL DIDÁTICO' },
  { value: '31', label: 'MATERIAIS - MATERIAL ESPORTIVO' },
  { value: '32', label: 'MATERIAIS - OUTROS MATERIAIS' },
  { value: '33', label: 'MATERIAL MÉDICO E HOSPITALAR - MATERIAL MÉDICO E HOSPITALAR' },
  { value: '34', label: 'MEDICAMENTOS - MEDICAMENTOS' },
  { value: '35', label: 'RECURSOS HUMANOS - 13º SALÁRIO' },
  { value: '36', label: 'RECURSOS HUMANOS - APRENDIZES' },
  { value: '37', label: 'RECURSOS HUMANOS - ASSISTÊNCIA MÉDICA' },
  { value: '38', label: 'RECURSOS HUMANOS - AVISO PRÉVIO' },
  { value: '39', label: 'RECURSOS HUMANOS - CONTRIBUIÇÃO AO INSS - COTA PATRONAL' },
  { value: '40', label: 'RECURSOS HUMANOS - CONTRIBUIÇÃO AO PIS' },
  { value: '41', label: 'RECURSOS HUMANOS - CURSOS/TREINAMENTO/RECICLAGEM' },
  { value: '42', label: 'RECURSOS HUMANOS - DIRETORIA (Salários e Ordenados)' },
  { value: '43', label: 'RECURSOS HUMANOS - ESTAGIÁRIOS' },
  { value: '44', label: 'RECURSOS HUMANOS - FÉRIAS' },
  { value: '45', label: 'RECURSOS HUMANOS - FGTS' },
  { value: '46', label: 'RECURSOS HUMANOS - GRATIFICAÇÕES' },
  { value: '47', label: 'RECURSOS HUMANOS - INDENIZAÇÕES' },
  { value: '48', label: 'RECURSOS HUMANOS - INSS' },
  { value: '49', label: 'RECURSOS HUMANOS - IRRF' },
  { value: '50', label: 'RECURSOS HUMANOS - MULTA RESCISÓRIA FGTS' },
  { value: '51', label: 'RECURSOS HUMANOS - SALÁRIOS E ORDENADOS (Exceto Diretoria)' },
  { value: '52', label: 'RECURSOS HUMANOS - VALE ALIMENTAÇÃO' },
  { value: '53', label: 'RECURSOS HUMANOS - VALE REFEIÇÃO' },
  { value: '54', label: 'RECURSOS HUMANOS - VALE TRANSPORTE' },
  { value: '55', label: 'RECURSOS HUMANOS - OUTRAS DESPESAS DE RECURSOS HUMANOS' },
  { value: '56', label: 'SERVIÇOS DE TERCEIROS - COLETA DE LIXO COMUM' },
  { value: '57', label: 'SERVIÇOS DE TERCEIROS - COLETA DE LIXO HOSPITALAR' },
  { value: '58', label: 'SERVIÇOS DE TERCEIROS - CONSULTORIA/ASSESSORIA CONTÁBIL' },
  { value: '59', label: 'SERVIÇOS DE TERCEIROS - CONSULTORIA/ASSESSORIA JURÍDICA' },
  { value: '60', label: 'SERVIÇOS DE TERCEIROS - LIMPEZA E CONSERVAÇÃO' },
  { value: '61', label: 'SERVIÇOS DE TERCEIROS - OBRAS/REFORMAS' },
  { value: '62', label: 'SERVIÇOS DE TERCEIROS - OUTROS SERVIÇOS DE TERCEIROS PESSOA FÍSICA' },
  { value: '63', label: 'SERVIÇOS DE TERCEIROS - OUTROS SERVIÇOS DE TERCEIROS PESSOA JURÍDICA' },
  { value: '64', label: 'SERVIÇOS DE TERCEIROS - PUBLICIDADE E PROPAGANDA' },
  { value: '65', label: 'SERVIÇOS DE TERCEIROS - SERVIÇO DE APOIO DIAGNÓSTICO TERAPÊUTICO (SADT)' },
  { value: '66', label: 'SERVIÇOS DE TERCEIROS - SERVIÇOS DE AUDITORIA' },
  { value: '67', label: 'SERVIÇOS DE TERCEIROS - SERVIÇOS DE TECNOLOGIA DA INFORMAÇÃO (TI)' },
  { value: '68', label: 'SERVIÇOS DE TERCEIROS - VIGILÂNCIA' },
  { value: '69', label: 'SERVIÇOS MÉDICOS - SERVIÇOS MÉDICOS PESSOA FÍSICA' },
  { value: '70', label: 'SERVIÇOS MÉDICOS - SERVIÇOS MÉDICOS PESSOA JURÍDICA' },
  { value: '71', label: 'UTILIDADES PÚBLICAS - ÁGUA E ESGOTO' },
  { value: '72', label: 'UTILIDADES PÚBLICAS - FORÇA E LUZ' },
  { value: '73', label: 'UTILIDADES PÚBLICAS - INTERNET/TV A CABO' },
  { value: '74', label: 'UTILIDADES PÚBLICAS - TELEFONES' },
  { value: '76', label: 'UTILIDADES PÚBLICAS - OUTRAS UTILIDADES PÚBLICAS' },
  { value: '77', label: 'DESPESAS DE CONVÊNIOS - CONTRATUALIZAÇÃO DE SERVIÇOS DOS SUS - DESPESAS DE CONVÊNIOS - CONTRATUALIZAÇÃO DE SERVIÇOS DOS SUS' },
  { value: '78', label: 'MANUTENÇÃO - MANUTENÇÃO DE MOBILIÁRIO E EQUIPAMENTOS' },
  { value: '79', label: 'MATERIAIS - MATERIAL DE HIGIENIZAÇÃO E LIMPEZA' },
  { value: '80', label: 'MATERIAIS - UNIFORMES' },
  { value: '81', label: 'MATERIAIS - EQUIPAMENTOS DE SEGURANÇA DO TRABALHO (EPI)' },
  { value: '82', label: 'MATERIAIS - ENXOVAL' },
  { value: '83', label: 'RECURSOS HUMANOS - ASSISTÊNCIA ODONTOLÓGICA' },
  { value: '84', label: 'RECURSOS HUMANOS - SEGUROS' },
  { value: '85', label: 'UTILIDADES PÚBLICAS - GÁS DE COZINHA' },
  { value: '86', label: 'MATERIAIS DE CONSUMO - BRINQUEDOS' },
  { value: '87', label: 'TRIBUTOS - ESTADUAIS (ICMS/IPVA/ITCMD/TAXAS E OUTROS)' },
  { value: '88', label: 'TRIBUTOS - FEDERAIS (IRRF/PIS/COFINS/CSLL/ITR/IOF/TAXAS E OUTROS)' },
  { value: '89', label: 'TRIBUTOS - MUNICIPAIS (IPTU/ISS/ITBI/TAXAS E OUTROS)' },
];

/** Pagamentos, Receitas, Empenhos e Ajustes de Saldo — `fonte_recurso_tipo`.
 * A série 91–98 repete a 1–8 para recursos de exercícios anteriores. */
export const FONTE_RECURSO: Opcao[] = [
  { value: '1', label: 'RECURSOS DO TESOURO' },
  { value: '2', label: 'TRANSFERÊNCIAS E CONVÊNIOS ESTADUAIS - VINCULADOS' },
  { value: '3', label: 'RECURSOS PRÓPRIOS DE FUNDOS ESPECIAIS DE DESPESA - VINCULADOS' },
  { value: '4', label: 'RECURSOS PRÓPRIOS DA ADMINISTRAÇÃO INDIRETA' },
  { value: '5', label: 'TRANSFERÊNCIAS E CONVÊNIOS FEDERAIS - VINCULADOS' },
  { value: '6', label: 'OUTRAS FONTES DE RECURSOS' },
  { value: '7', label: 'OPERAÇÕES DE CRÉDITO' },
  { value: '8', label: 'EMENDAS PARLAMENTARES INDIVIDUAIS - LEGISLATIVO MUNICIPAL' },
  { value: '91', label: 'TESOURO - EXERCÍCIOS ANTERIORES' },
  { value: '92', label: 'TRANSFERÊNCIAS E CONVÊNIOS ESTADUAIS - VINCULADOS - EXERCÍCIOS ANTERIORES' },
  { value: '93', label: 'RECURSOS PRÓPRIOS DE FUNDOS ESPECIAIS DE DESPESA - VINCULADOS - EXERCÍCIOS ANTERIORES' },
  { value: '94', label: 'RECURSOS PRÓPRIOS DA ADMINISTRAÇÃO INDIRETA - EXERCÍCIOS ANTERIORES' },
  { value: '95', label: 'TRANSFERÊNCIAS E CONVÊNIOS FEDERAIS - VINCULADOS - EXERCÍCIOS ANTERIORES' },
  { value: '96', label: 'OUTRAS FONTES DE RECURSOS - EXERCÍCIOS ANTERIORES' },
  { value: '97', label: 'OPERAÇÕES DE CRÉDITO - EXERCÍCIOS ANTERIORES' },
  { value: '98', label: 'EMENDAS PARLAMENTARES INDIVIDUAIS - EXERCÍCIOS ANTERIORES' },
];

/** Documentos fiscais — `estado_emissor` (UF do emissor). */
export const ESTADO_EMISSOR: Opcao[] = [
  { value: '1', label: 'AC' },
  { value: '2', label: 'AL' },
  { value: '3', label: 'AM' },
  { value: '4', label: 'AP' },
  { value: '5', label: 'BA' },
  { value: '6', label: 'CE' },
  { value: '7', label: 'DF' },
  { value: '8', label: 'ES' },
  { value: '9', label: 'GO' },
  { value: '10', label: 'MA' },
  { value: '11', label: 'MG' },
  { value: '12', label: 'MS' },
  { value: '13', label: 'MT' },
  { value: '14', label: 'PA' },
  { value: '15', label: 'PB' },
  { value: '16', label: 'PE' },
  { value: '17', label: 'PI' },
  { value: '18', label: 'PR' },
  { value: '19', label: 'RJ' },
  { value: '20', label: 'RN' },
  { value: '21', label: 'RO' },
  { value: '22', label: 'RR' },
  { value: '23', label: 'RS' },
  { value: '24', label: 'SC' },
  { value: '25', label: 'SE' },
  { value: '26', label: 'SP' },
  { value: '27', label: 'TO' },
];

/** Contratos — `natureza_contratacao` (aceita vários códigos por contrato). */
export const NATUREZA_CONTRATACAO: Opcao[] = [
  { value: '1', label: 'Abastecimento de água' },
  { value: '2', label: 'Alimentação' },
  { value: '3', label: 'Aquisição de bens' },
  { value: '4', label: 'Assessoria/consultoria' },
  { value: '5', label: 'Bens e serviços de informática' },
  { value: '6', label: 'Coleta de lixo comum' },
  { value: '7', label: 'Coleta de lixo hospitalar' },
  { value: '8', label: 'Combustível' },
  { value: '9', label: 'Contabilidade' },
  { value: '10', label: 'Demais encargos sociais' },
  { value: '11', label: 'FGTS' },
  { value: '12', label: 'Gêneros alimentícios' },
  { value: '13', label: 'Impostos' },
  { value: '14', label: 'INSS - contribuição patronal' },
  { value: '15', label: 'INSS - empregado' },
  { value: '16', label: 'Licença de uso de software' },
  { value: '17', label: 'Limpeza e conservação' },
  { value: '18', label: 'Locação de Equipamentos' },
  { value: '19', label: 'Locação de Imóveis' },
  { value: '20', label: 'Material hospitalar' },
  { value: '21', label: 'Medicamentos' },
  { value: '22', label: 'Obras e reformas' },
  { value: '23', label: 'Outros Serviços' },
  { value: '24', label: 'Permissão de uso/serviço' },
  { value: '25', label: 'Prestação de serviços' },
  { value: '26', label: 'Publicidade/Propaganda' },
  { value: '27', label: 'Serviço de Arquivamento' },
  { value: '28', label: 'Serviço de engenharia' },
  { value: '29', label: 'Serviços clínicos-laboratoriais' },
  { value: '30', label: 'Serviços Jurídicos' },
  { value: '31', label: 'Serviços Médicos' },
  { value: '32', label: 'Telefone/Internet/Tv a Cabo' },
  { value: '33', label: 'Transporte' },
  { value: '34', label: 'Vale/Auxílio Alimentação' },
  { value: '35', label: 'Veículos e afins' },
  { value: '36', label: 'Vigilância' },
];

/** Contratos — `criterio_selecao`. */
export const CRITERIO_SELECAO: Opcao[] = [
  { value: '1', label: 'Cotação de Preços' },
  { value: '2', label: 'Dispensa' },
  { value: '3', label: 'Inexigibilidade' },
  { value: '4', label: 'Outros' },
];

/** Contratos — `valor_tipo`. */
export const VALOR_TIPO: Opcao[] = [
  { value: '1', label: 'Global' },
  { value: '2', label: 'Mensal' },
];

/** Contratos — `vigencia_tipo`. */
export const VIGENCIA_TIPO: Opcao[] = [
  { value: '1', label: 'Pré-Estabelecida' },
  { value: '2', label: 'Indeterminada' },
];

/** Disponibilidades — `conta_tipo`. */
export const CONTA_TIPO: Opcao[] = [
  { value: '1', label: 'Conta Corrente' },
  { value: '2', label: 'Investimento' },
];

/** Devoluções — `natureza_devolucao_tipo`. */
export const NATUREZA_DEVOLUCAO: Opcao[] = [
  { value: '1', label: 'Glosa devolvida à conta bancária específica do repasse público' },
  { value: '2', label: 'Glosa devolvida à conta bancária do órgão público' },
  { value: '3', label: 'Valor não aplicado' },
];

/** Repasses — `tipo_documento_bancario`. */
export const TIPO_DOCUMENTO_BANCARIO: Opcao[] = [
  { value: '1', label: 'Ordem bancária' },
  { value: '2', label: 'Outros' },
  { value: '3', label: 'Cheque' },
];

/** Servidores cedidos — `onus_pagamento`. */
export const ONUS_PAGAMENTO: Opcao[] = [
  { value: '1', label: 'Órgão Concessor' },
  { value: '2', label: 'Entidade Beneficiada' },
  { value: '3', label: 'Ambos' },
];

/** `documento_tipo` como código numérico. Na maioria dos blocos esse campo é
 * um enum do Prisma (ver `TIPO_DOCUMENTO` em `dominios.ts`); nos Ajustes de
 * Saldo, que guardam arrays Json crus, é gravado como número. */
export const DOCUMENTO_TIPO_COD: Opcao[] = [
  { value: '1', label: 'CPF' },
  { value: '2', label: 'CNPJ' },
  { value: '3', label: 'RNE' },
];

/** `meio_pagamento_tipo` como código numérico (mesma observação acima). */
export const MEIO_PAGAMENTO_COD: Opcao[] = [
  { value: '1', label: 'BANCO' },
  { value: '2', label: 'FUNDO FIXO' },
];

/** Bancos aceitos em Pagamentos, Disponibilidades e Repasses. */
export const BANCO: Opcao[] = [
  { value: '1', label: 'BANCO DO BRASIL S.A.' },
  { value: '2', label: 'BANCO CENTRAL DO BRASIL SA' },
  { value: '3', label: 'BANCO DA AMAZONIA S.A.' },
  { value: '4', label: 'BANCO DO NORDESTE DO BRASIL S.A.' },
  { value: '7', label: 'BNDES' },
  { value: '8', label: 'BANCO SANTANDER MERIDIONAL S.A.' },
  { value: '10', label: 'CREDICOAMO' },
  { value: '11', label: 'C.SUISSE HEDGING-GRIFFO CV S/A' },
  { value: '12', label: 'BANCO INBURSA' },
  { value: '14', label: 'STATE STREET BR S.A. BANCO COMERCIAL' },
  { value: '15', label: 'UBS BRASIL CCTVM S.A.' },
  { value: '16', label: 'CCM DESP TRÂNS SC E RS' },
  { value: '17', label: 'BNY MELLON BANCO S.A.' },
  { value: '18', label: 'BANCO TRICURY S.A.' },
  { value: '21', label: 'BANCO BANESTES S.A.' },
  { value: '24', label: 'BANCO BANDEPE S.A.' },
  { value: '25', label: 'BANCO ALFA S.A.' },
  { value: '27', label: 'BANCO DO ESTADO DE SANTA CATARINA SA' },
  { value: '29', label: 'BANCO ITAÚ CONSIGNADO S.A.' },
  { value: '31', label: 'BANCO BEG S.A.' },
  { value: '33', label: 'BANCO SANTANDER (BRASIL) S.A.' },
  { value: '35', label: 'BANCO BEC S/A.' },
  { value: '36', label: 'BANCO BBI S.A.' },
  { value: '37', label: 'BANCO DO ESTADO DO PARA S.A.' },
  { value: '38', label: 'BANCO BANESTADO S.A.' },
  { value: '39', label: 'BANCO DO ESTADO DO PIAUI SA' },
  { value: '40', label: 'BANCO CARGILL S.A.' },
  { value: '41', label: 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.' },
  { value: '44', label: 'BANCO BVA S/A' },
  { value: '45', label: 'BANCO OPPORTUNITY S.A.' },
  { value: '47', label: 'BANCO DO ESTADO DE SERGIPE S.A.' },
  { value: '60', label: 'CONFIDENCE CC S.A.' },
  { value: '62', label: 'HIPERCARD BM S.A.' },
  { value: '63', label: 'BANCO BRADESCARD' },
  { value: '64', label: 'GOLDMAN SACHS DO BRASIL BM S.A' },
  { value: '65', label: 'BANCO ANDBANK S.A.' },
  { value: '66', label: 'BANCO MORGAN STANLEY S.A.' },
  { value: '69', label: 'BANCO CREFISA S.A.' },
  { value: '70', label: 'BRB - BANCO DE BRASILIA S.A.' },
  { value: '72', label: 'BANCO RURAL MAIS S.A.' },
  { value: '73', label: 'BB BANCO POPULAR DO BRASIL S.A' },
  { value: '74', label: 'BANCO J.SAFRA S.A.' },
  { value: '75', label: 'BANCO ABN AMRO S.A.' },
  { value: '76', label: 'BANCO KDB BRASIL S.A.' },
  { value: '77', label: 'BANCO INTER' },
  { value: '78', label: 'HAITONG BI DO BRASIL S.A.' },
  { value: '79', label: 'PICPAY BANK - BANCO MÚLTIPLO S.A' },
  { value: '80', label: 'B&T CC LTDA.' },
  { value: '81', label: 'BANCOSEGURO S.A.' },
  { value: '82', label: 'BANCO TOPÁZIO S.A.' },
  { value: '83', label: 'BANCO DA CHINA BRASIL S.A.' },
  { value: '84', label: 'UNIPRIME DO BRASIL - COOP' },
  { value: '85', label: 'COOPCENTRAL AILOS' },
  { value: '87', label: 'Cooperativa Central de Economia e Crédito Mútuo das Unicreds de Santa Catarina e Paraná' },
  { value: '88', label: 'BANCO RANDON S.A.' },
  { value: '89', label: 'CREDISAN CC' },
  { value: '90', label: 'Cooperativa Central de Economia e Crédito Mutuo das Unicreds' },
  { value: '92', label: 'BRK S.A. CFI' },
  { value: '93', label: 'POLOCRED SCMEPP LTDA.' },
  { value: '94', label: 'BANCO FINAXIS' },
  { value: '95', label: 'TRAVELEX BANCO DE CÂMBIO S.A.' },
  { value: '96', label: 'BANCO B3 S.A.' },
  { value: '97', label: 'CREDISIS CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.' },
  { value: '98', label: 'CREDIALIANÇA CCR' },
  { value: '99', label: 'UNIPRIME COOPCENTRAL LTDA.' },
  { value: '100', label: 'PLANNER CV S.A.' },
  { value: '101', label: 'RENASCENCA DTVM LTDA' },
  { value: '102', label: 'XP INVESTIMENTOS CCTVM S/A' },
  { value: '104', label: 'CAIXA ECONOMICA FEDERAL' },
  { value: '105', label: 'LECCA CFI S.A.' },
  { value: '107', label: 'BANCO BOCOM BBM S.A.' },
  { value: '108', label: 'PORTOCRED S.A. - CFI' },
  { value: '111', label: 'OLIVEIRA TRUST DTVM S.A.' },
  { value: '113', label: 'NEON CTVM S.A.' },
  { value: '114', label: 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO' },
  { value: '116', label: 'BANCO UNICO S.A.' },
  { value: '117', label: 'ADVANCED CC LTDA' },
  { value: '119', label: 'BANCO WESTERN UNION' },
  { value: '120', label: 'BANCO RODOBENS S.A.' },
  { value: '121', label: 'BANCO AGIBANK S.A.' },
  { value: '122', label: 'BANCO BRADESCO BERJ S.A.' },
  { value: '124', label: 'BANCO WOORI BANK DO BRASIL S.A.' },
  { value: '125', label: 'BANCO GENIAL' },
  { value: '126', label: 'BR PARTNERS BI' },
  { value: '127', label: 'CODEPE CVC S.A.' },
  { value: '128', label: 'MS BANK S.A. BANCO DE CÂMBIO' },
  { value: '129', label: 'UBS BRASIL BI S.A.' },
  { value: '130', label: 'CARUANA SCFI' },
  { value: '131', label: 'TULLETT PREBON BRASIL CVC LTDA' },
  { value: '132', label: 'ICBC DO BRASIL BM S.A.' },
  { value: '133', label: 'CRESOL CONFEDERAÇÃO' },
  { value: '134', label: 'BGC LIQUIDEZ DTVM LTDA' },
  { value: '135', label: 'GRADUAL CORRETORA' },
  { value: '136', label: 'CONF NAC COOP CENTRAIS UNICRED' },
  { value: '138', label: 'GET MONEY CC LTDA' },
  { value: '139', label: 'INTESA SANPAOLO BRASIL S.A. BM' },
  { value: '140', label: 'NU INVEST CORRETORA DE VALORES S.A.' },
  { value: '141', label: 'BANCO MASTER DE INVESTIMENTO S.A.' },
  { value: '142', label: 'BROKER BRASIL CC LTDA.' },
  { value: '143', label: 'TREVISO CC S.A.' },
  { value: '144', label: 'BEXS BANCO DE CAMBIO S.A.' },
  { value: '145', label: 'LEVYCAM CCV LTDA' },
  { value: '146', label: 'GUITTA CC LTDA' },
  { value: '149', label: 'FACTA S.A. CFI' },
  { value: '151', label: 'BANCO NOSSA CAIXA' },
  { value: '157', label: 'ICAP DO BRASIL CTVM LTDA.' },
  { value: '159', label: 'CASA CREDITO S.A. SCM' },
  { value: '163', label: 'COMMERZBANK BRASIL S.A. - BANCO MÚLTIPLO' },
  { value: '173', label: 'BRL TRUST DTVM SA' },
  { value: '174', label: 'PEFISA S.A. - C.F.I.' },
  { value: '175', label: 'BANCO FINASA S/A' },
  { value: '177', label: 'GUIDE' },
  { value: '180', label: 'CM CAPITAL MARKETS CCTVM LTDA' },
  { value: '183', label: 'SOCRED SA - SCMEPP' },
  { value: '184', label: 'BANCO ITAÚ BBA S.A.' },
  { value: '188', label: 'ATIVA S.A. INVESTIMENTOS CCTVM' },
  { value: '189', label: 'HS FINANCEIRA' },
  { value: '190', label: 'SERVICOOP' },
  { value: '191', label: 'NOVA FUTURA CTVM LTDA.' },
  { value: '194', label: 'PARMETAL DTVM LTDA' },
  { value: '195', label: 'VALOR SCD S.A.' },
  { value: '196', label: 'FAIR CC S.A.' },
  { value: '197', label: 'STONE IP S.A.' },
  { value: '204', label: 'AMERICAN EXPRESS BANK(BR) BANCO MULTIPLO' },
  { value: '208', label: 'BANCO BTG PACTUAL S.A.' },
  { value: '210', label: 'DRESDNER BANK LATEINAMERIKA S.A' },
  { value: '212', label: 'BANCO ORIGINAL' },
  { value: '213', label: 'BANCO ARBI S.A.' },
  { value: '214', label: 'BANCO DIBENS SA' },
  { value: '215', label: 'BANCO COML INV SUDAMERIS SA' },
  { value: '217', label: 'BANCO JOHN DEERE S.A.' },
  { value: '218', label: 'BANCO BS2 S.A.' },
  { value: '222', label: 'BANCO CRÉDIT AGRICOLE BR S.A.' },
  { value: '224', label: 'BANCO FIBRA S.A.' },
  { value: '225', label: 'BANCO BRASCAN SA.' },
  { value: '229', label: 'BANCO CRUZEIRO S.A.' },
  { value: '230', label: 'UNICARD BANCO MULTIPLO' },
  { value: '233', label: 'BANCO CIFRA' },
  { value: '237', label: 'BANCO BRADESCO S.A.' },
  { value: '241', label: 'BANCO CLASSICO S.A.' },
  { value: '243', label: 'BANCO MASTER' },
  { value: '244', label: 'BANCO CIDADE SA' },
  { value: '246', label: 'BANCO ABC BRASIL S.A.' },
  { value: '247', label: 'BANCO UBS WARBURG S/A' },
  { value: '248', label: 'BANCO BOAVISTA INTERATLANTICO SA' },
  { value: '249', label: 'BANCO INVESTCRED UNIBANCO S.A.' },
  { value: '250', label: 'BCV - BCO, CRÉDITO E VAREJO S.A.' },
  { value: '252', label: 'BANCO FININVEST SA' },
  { value: '253', label: 'BEXS CC S.A.' },
  { value: '254', label: 'PARANA BANCO S.A.' },
  { value: '259', label: 'MONEYCORP BANCO DE CÂMBIO S.A.' },
  { value: '260', label: 'NU PAGAMENTOS - IP' },
  { value: '263', label: 'BANCO CACIQUE SA' },
  { value: '265', label: 'BANCO FATOR S.A.' },
  { value: '266', label: 'BANCO CEDULA S.A.' },
  { value: '268', label: 'BARI CIA HIPOTECÁRIA' },
  { value: '269', label: 'BANCO HSBC S.A.' },
  { value: '270', label: 'SAGITUR CC' },
  { value: '271', label: 'IB CCTVM S.A.' },
  { value: '272', label: 'AGK CC S.A.' },
  { value: '273', label: 'CCR DE SÃO MIGUEL DO OESTE' },
  { value: '274', label: 'MONEY PLUS SCMEPP LTDA' },
  { value: '276', label: 'BANCO SENFF S.A.' },
  { value: '278', label: 'GENIAL INVESTIMENTOS CVM S.A.' },
  { value: '279', label: 'CCR DE PRIMAVERA DO LESTE' },
  { value: '280', label: 'WILL FINANCEIRA S.A.CFI' },
  { value: '281', label: 'CCR COOPAVEL' },
  { value: '283', label: 'RB INVESTIMENTOS DTVM LTDA.' },
  { value: '285', label: 'FRENTE CC LTDA.' },
  { value: '286', label: 'CCR DE OURO' },
  { value: '288', label: 'CAROL DTVM LTDA.' },
  { value: '289', label: 'EFX CC LTDA.' },
  { value: '290', label: 'PAGSEGURO INTERNET IP S.A.' },
  { value: '291', label: 'BANCO BCN S.A.' },
  { value: '292', label: 'BS2 DTVM S.A.' },
  { value: '293', label: 'LASTRO RDV DTVM LTDA' },
  { value: '296', label: 'OZ CORRETORA DE CÂMBIO S.A.' },
  { value: '298', label: 'VIPS CC LTDA.' },
  { value: '299', label: 'BANCO SOROCRED S.A. - BM' },
  { value: '300', label: 'BANCO LA NACION ARGENTINA' },
  { value: '301', label: 'BPP IP S.A.' },
  { value: '306', label: 'PORTOPAR DTVM LTDA' },
  { value: '307', label: 'TERRA INVESTIMENTOS DTVM' },
  { value: '309', label: 'CAMBIONET CC LTDA' },
  { value: '310', label: 'VORTX DTVM LTDA.' },
  { value: '311', label: 'DOURADA CORRETORA' },
  { value: '312', label: 'HSCM SCMEPP LTDA.' },
  { value: '313', label: 'AMAZÔNIA CC LTDA.' },
  { value: '318', label: 'BANCO BMG S.A.' },
  { value: '319', label: 'OM DTVM LTDA' },
  { value: '320', label: 'BANCO CCB BRASIL S.A.' },
  { value: '321', label: 'CREFAZ SCMEPP LTDA' },
  { value: '322', label: 'CCR DE ABELARDO LUZ' },
  { value: '323', label: 'MERCADO PAGO IP LTDA.' },
  { value: '324', label: 'CARTOS SCD S.A.' },
  { value: '325', label: 'ÓRAMA DTVM S.A.' },
  { value: '326', label: 'PARATI - CFI S.A.' },
  { value: '328', label: 'CECM FABRIC CALÇADOS SAPIRANGA' },
  { value: '329', label: 'QI SCD S.A.' },
  { value: '330', label: 'BANCO BARI S.A.' },
  { value: '331', label: 'FRAM CAPITAL DTVM S.A.' },
  { value: '332', label: 'ACESSO SOLUCOES PAGAMENTO SA' },
  { value: '334', label: 'BANCO BESA S.A.' },
  { value: '335', label: 'BANCO DIGIO' },
  { value: '336', label: 'BANCO C6 S.A.' },
  { value: '340', label: 'SUPERDIGITAL I.P. S.A.' },
  { value: '341', label: 'ITAÚ UNIBANCO S.A.' },
  { value: '342', label: 'CREDITAS SCD' },
  { value: '343', label: 'FFA SCMEPP LTDA.' },
  { value: '347', label: 'BANCO SUDAMERIS BRASIL SA' },
  { value: '348', label: 'BANCO XP S.A.' },
  { value: '349', label: 'AL5 S.A. CFI' },
  { value: '350', label: 'CREHNOR LARANJEIRAS' },
  { value: '351', label: 'BANCO SANTANDER S/A' },
  { value: '352', label: 'TORO CTVM S.A.' },
  { value: '353', label: 'BANCO SANTANDER BRASIL S.A.' },
  { value: '354', label: 'NECTON INVESTIMENTOS S.A CVM' },
  { value: '355', label: 'ÓTIMO SCD S.A.' },
  { value: '356', label: 'BANCO ABN AMRO REAL S.A.' },
  { value: '358', label: 'MIDWAY S.A. - SCFI' },
  { value: '359', label: 'ZEMA CFI S/A' },
  { value: '360', label: 'TRINUS CAPITAL DTVM' },
  { value: '362', label: 'CIELO S.A.' },
  { value: '363', label: 'SINGULARE CTVM S.A.' },
  { value: '364', label: 'GERENCIANET' },
  { value: '365', label: 'SIMPAUL' },
  { value: '366', label: 'BANCO SOCIETE GENERALE BRASIL' },
  { value: '367', label: 'VITREO DTVM S.A.' },
  { value: '368', label: 'BANCO CSF S.A.' },
  { value: '370', label: 'BANCO MIZUHO S.A.' },
  { value: '371', label: 'WARREN CVMC LTDA' },
  { value: '373', label: 'UP.P SEP S.A.' },
  { value: '374', label: 'REALIZE CFI S.A.' },
  { value: '376', label: 'BANCO J.P. MORGAN S.A.' },
  { value: '377', label: 'BMS SCD S.A.' },
  { value: '378', label: 'BANCO BRASILEIRO DE CRÉDITO S.A.' },
  { value: '379', label: 'CECM COOPERFORTE' },
  { value: '380', label: 'PICPAY' },
  { value: '381', label: 'BANCO MERCEDES-BENZ S.A.' },
  { value: '382', label: 'FIDUCIA SCMEPP LTDA' },
  { value: '383', label: 'EBANX IP LTDA.' },
  { value: '384', label: 'GLOBAL SCM LTDA' },
  { value: '385', label: 'CECM DOS TRAB.PORT. DA G.VITOR' },
  { value: '386', label: 'NU FINANCEIRA S.A. CFI' },
  { value: '387', label: 'BANCO TOYOTA DO BRASIL S.A.' },
  { value: '389', label: 'BANCO MERCANTIL DO BRASIL S.A.' },
  { value: '390', label: 'BANCO GM S.A.' },
  { value: '391', label: 'CCR DE IBIAM' },
  { value: '392', label: 'BANCO MERCANTIL DE SÃO PAULO S.A.' },
  { value: '393', label: 'BANCO VOLKSWAGEN S.A' },
  { value: '394', label: 'BANCO BRADESCO FINANC. S.A.' },
  { value: '395', label: 'F D GOLD DTVM LTDA' },
  { value: '396', label: 'HUB PAGAMENTOS' },
  { value: '397', label: 'LISTO SCD S.A.' },
  { value: '398', label: 'IDEAL CTVM S.A.' },
  { value: '399', label: 'KIRTON BANK' },
  { value: '400', label: 'COOP CREDITAG' },
  { value: '401', label: 'IUGU IP S.A.' },
  { value: '402', label: 'COBUCCIO SCD S.A.' },
  { value: '403', label: 'CORA SCD S.A.' },
  { value: '404', label: 'SUMUP SCD S.A.' },
  { value: '406', label: 'ACCREDITO SCD S.A.' },
  { value: '407', label: 'ÍNDIGO INVESTIMENTOS DTVM LTDA.' },
  { value: '408', label: 'BONUSPAGO SCD S.A.' },
  { value: '409', label: 'BANCO UNIBANCO SA' },
  { value: '410', label: 'PLANNER SCM S.A.' },
  { value: '411', label: 'VIA CERTA FINANCIADORA S.A. - CFI' },
  { value: '412', label: 'SOCIAL BANK S/A' },
  { value: '413', label: 'BANCO BV S.A.' },
  { value: '414', label: 'WORK SCD S.A.' },
  { value: '416', label: 'LAMARA SCD S.A.' },
  { value: '418', label: 'ZIPDIN SCD S.A.' },
  { value: '419', label: 'NUMBRS SCD S.A.' },
  { value: '421', label: 'CC LAR CREDI' },
  { value: '422', label: 'BANCO SAFRA S.A.' },
  { value: '423', label: 'COLUNA S.A. DTVM' },
  { value: '425', label: 'SOCINAL S.A. CFI' },
  { value: '426', label: 'BIORC FINANCEIRA - CFI S.A.' },
  { value: '427', label: 'CRED-UFES' },
  { value: '428', label: 'CREDSYSTEM SCD S.A.' },
  { value: '429', label: 'CREDIARE CFI S.A.' },
  { value: '430', label: 'CCR SEARA' },
  { value: '433', label: 'BR-CAPITAL DTVM S.A.' },
  { value: '435', label: 'DELCRED SCD S.A.' },
  { value: '438', label: 'TRUSTEE DTVM LTDA.' },
  { value: '439', label: 'ID CTVM' },
  { value: '440', label: 'CREDIBRF COOP' },
  { value: '442', label: 'MAGNETIS - DTVM' },
  { value: '443', label: 'CREDIHOME SCD' },
  { value: '444', label: 'TRINUS SCD S.A.' },
  { value: '445', label: 'PLANTAE CFI' },
  { value: '447', label: 'MIRAE ASSET CCTVM LTDA' },
  { value: '448', label: 'HEMERA DTVM LTDA.' },
  { value: '449', label: 'DMCARD SCD S.A.' },
  { value: '450', label: 'FITBANK PAGAMENTOS ELETRONICOS S.A.' },
  { value: '451', label: 'J17 - SCD S/A' },
  { value: '452', label: 'CREDIFIT SCD S.A.' },
  { value: '453', label: 'BANCO RURAL SA' },
  { value: '454', label: 'MÉRITO DTVM LTDA.' },
  { value: '456', label: 'BANCO MUFG BRASIL S.A.' },
  { value: '457', label: 'UY3 SCD S/A' },
  { value: '458', label: 'HEDGE INVESTMENTS DTVM LTDA.' },
  { value: '459', label: 'CCM SERV. PÚBLICOS SP' },
  { value: '460', label: 'UNAVANTI SCD S/A' },
  { value: '461', label: 'ASAAS IP S.A.' },
  { value: '462', label: 'STARK SCD S.A.' },
  { value: '463', label: 'AZUMI DTVM' },
  { value: '464', label: 'BANCO SUMITOMO MITSUI BRASIL S.A.' },
  { value: '465', label: 'CAPITAL CONSIG SCD S.A.' },
  { value: '467', label: 'MASTER S/A CCTVM' },
  { value: '468', label: 'PORTOSEG S.A. CFI' },
  { value: '469', label: 'LIGA INVEST DTVM LTDA.' },
  { value: '470', label: 'CDC SOCIEDADE DE CRÉDITO' },
  { value: '471', label: 'CECM SERV PUBL PINHÃO' },
  { value: '473', label: 'BANCO CAIXA GERAL BRASIL S.A.' },
  { value: '475', label: 'BANCO YAMAHA MOTOR S.A.' },
  { value: '477', label: 'CITIBANK N.A.' },
  { value: '478', label: 'GAZINCRED S.A. SCFI' },
  { value: '479', label: 'BANCO ITAUBANK S.A.' },
  { value: '481', label: 'SUPERLÓGICA SCD S.A.' },
  { value: '484', label: 'MAF DTVM SA' },
  { value: '487', label: 'DEUTSCHE BANK S.A.BANCO ALEMAO' },
  { value: '488', label: 'JPMORGAN CHASE BANK' },
  { value: '492', label: 'ING BANK N.V.' },
  { value: '494', label: 'BANCO LA REPUBL.ORIENTAL DEL URUGUAY SA' },
  { value: '495', label: 'BANCO LA PROVINCIA B AIRES BCE' },
  { value: '505', label: 'BANCO CREDIT SUISSE S.A.' },
  { value: '506', label: 'RJI' },
  { value: '508', label: 'AVENUE SECURITIES DTVM LTDA.' },
  { value: '509', label: 'CELCOIN INSTITUICAO DE PAGAMENTO S.A.' },
  { value: '511', label: 'MAGNUM SCD' },
  { value: '512', label: 'CAPTALYS DTVM LTDA.' },
  { value: '518', label: 'MERCADO CRÉDITO SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' },
  { value: '521', label: 'PEAK SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.' },
  { value: '522', label: 'RED SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '523', label: 'HR DIGITAL - SOCIEDADE DE CRÉDITO DIRETO S/A' },
  { value: '524', label: 'WNT CAPITAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { value: '526', label: 'MONETARIE SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '527', label: 'ATICCA - SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '528', label: 'REAG DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' },
  { value: '529', label: 'PINBANK' },
  { value: '530', label: 'SER FINANCE SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '532', label: 'EAGLE SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '534', label: 'EWALLY INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { value: '535', label: 'MARÚ SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '536', label: 'NEON PAGAMENTOS S.A. - INSTITUIÇÃO DE PAGAMENTO' },
  { value: '537', label: 'MICROCASH SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE' },
  { value: '539', label: 'SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTOS' },
  { value: '541', label: 'FUNDO GARANTIDOR DE CREDITOS - FGC' },
  { value: '542', label: 'CLOUDWALK INSTITUIÇÃO DE PAGAMENTO E SERVICOS LTDA' },
  { value: '545', label: 'SENSO CCVM S.A.' },
  { value: '546', label: 'U4C INSTITUIÇÃO DE PAGAMENTO S.A.' },
  { value: '547', label: 'BNK DIGITAL SOCIEDADE DE CRÉDITO DIRETO S.A.' },
  { value: '600', label: 'BANCO LUSO BRASILEIRO S.A.' },
  { value: '604', label: 'BANCO INDUSTRIAL DO BRASIL S.A.' },
  { value: '610', label: 'BANCO VR S.A.' },
  { value: '611', label: 'BANCO PAULISTA S.A.' },
  { value: '612', label: 'BANCO GUANABARA S.A.' },
  { value: '613', label: 'OMNI BANCO S.A.' },
  { value: '623', label: 'BANCO PAN' },
  { value: '626', label: 'BANCO C6 CONSIG' },
  { value: '630', label: 'BANCO LETSBANK S.A.' },
  { value: '633', label: 'BANCO RENDIMENTO S.A.' },
  { value: '634', label: 'BANCO TRIANGULO S.A.' },
  { value: '637', label: 'BANCO SOFISA S.A.' },
  { value: '638', label: 'BANCO PROSPER SA' },
  { value: '641', label: 'BANCO ALVORADA S.A.' },
  { value: '643', label: 'BANCO PINE S.A.' },
  { value: '650', label: 'BANCO PEBB S.A.' },
  { value: '652', label: 'ITAÚ UNIBANCO HOLDING S.A.' },
  { value: '653', label: 'BANCO VOITER' },
  { value: '654', label: 'BANCO DIGIMAIS S.A.' },
  { value: '655', label: 'BANCO VOTORANTIM S.A.' },
  { value: '707', label: 'BANCO DAYCOVAL S.A' },
  { value: '712', label: 'BANCO OURINVEST S.A.' },
  { value: '719', label: 'BANIF-BANCO INTERNACIONAL DO FUNCHAL(BR) S.A' },
  { value: '720', label: 'BANCO RNX S.A.' },
  { value: '721', label: 'BANCO CREDIBEL S.A.' },
  { value: '724', label: 'BANCO PORTO SEGURO S.A.' },
  { value: '734', label: 'BANCO GERDAU SA' },
  { value: '735', label: 'BANCO POTTENCIAL S.A.' },
  { value: '738', label: 'BANCO MORADA SA' },
  { value: '739', label: 'BANCO CETELEM S.A.' },
  { value: '740', label: 'BANCO BARCLAYS  S.A.' },
  { value: '741', label: 'BANCO RIBEIRAO PRETO S.A.' },
  { value: '743', label: 'BANCO SEMEAR' },
  { value: '744', label: 'BANKBOSTON N.A.' },
  { value: '745', label: 'BANCO CITIBANK S.A.' },
  { value: '746', label: 'BANCO MODAL S.A.' },
  { value: '747', label: 'BANCO RABOBANK INTL BRASIL S.A.' },
  { value: '748', label: 'BANCO COOPERATIVO SICREDI S.A.' },
  { value: '749', label: 'BANCO SIMPLES S.A.' },
  { value: '751', label: 'SCOTIABANK BRASIL' },
  { value: '752', label: 'BANCO BNP PARIBAS BRASIL S A' },
  { value: '753', label: 'NOVO BANCO CONTINENTAL S.A. - BM' },
  { value: '754', label: 'BANCO SISTEMA' },
  { value: '755', label: 'BOFA MERRILL LYNCH BM S.A.' },
  { value: '756', label: 'BANCO SICOOB S.A.' },
  { value: '757', label: 'BANCO KEB HANA DO BRASIL S.A.' },
  { value: '999', label: 'Instituição Financeira (não bancária)' },
];

/** Códigos "Outros", que exigem a descrição no campo livre correspondente. */
export const NATUREZA_CONTRATACAO_OUTROS = 23;
export const CRITERIO_SELECAO_OUTROS = 4;
export const TIPO_DOCUMENTO_BANCARIO_OUTROS = 2;

/** Rótulo de um código, para exibição em grades. Vazio quando não há valor. */
export function rotulo(tabela: Opcao[], codigo: number | string | null | undefined): string {
  if (codigo == null || codigo === '') return '';
  const achado = tabela.find((o) => o.value === String(codigo));
  return achado ? achado.label : `${codigo} (código inválido)`;
}
